//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string GearType { get; set; }
        public Nullable<int> Year { get; set; }
        public string Colour { get; set; }
        public string FuelType { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<int> SubstationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
