//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string NameSurname { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public string Password { get; set; }
    }
}
