//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeesID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public string Mail { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Password { get; set; }
        public Nullable<int> SubstationID { get; set; }
    }
}
